# version: '3.9'

services:
  timexo-web:
    build: .
    container_name: timexo-web
    command: gunicorn mkart.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - timexo-db
    environment:
      DJANGO_SETTINGS_MODULE: mkart.settings.prod
    expose:
      - "8000"
    restart: always
    networks:
      - server-network

  timexo-db:
    image: postgres:15
    container_name: timexo-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mkart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mnbmnb
    restart: always
    networks:
      - server-network

volumes:
  postgres_data:
  static_volume:

networks:
  server-network:
    external: true