# Generated by Django 5.0.7 on 2024-09-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_offer_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer',
        ),
    ]
