# Generated by Django 5.0.7 on 2024-08-29 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_offer'),
        ('products', '0003_remove_productvariant_offer_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.offer'),
        ),
    ]
