# Generated by Django 5.0.7 on 2024-09-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
