# Generated by Django 5.0.7 on 2024-09-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_brand_logo_remove_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='logo',
        ),
    ]
