# Generated by Django 5.0.7 on 2024-09-08 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_user_coupon_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user_coupon_limit',
            index=models.Index(fields=['user', 'coupon'], name='Admin_user__user_id_21b081_idx'),
        ),
    ]
