# Generated by Django 5.0.7 on 2026-07-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_wallettransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
