# Generated by Django 5.0.7 on 2024-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_coupon_order_discount_amount_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount_coupon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
