# Generated by Django 5.0.7 on 2024-09-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orderitem_discount_amount_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_amount_coupon',
        ),
    ]
