# Generated by Django 5.0.7 on 2024-09-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
