# Generated by Django 5.0.7 on 2026-05-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_order_options'),
        ('products', '0009_alter_productvariant_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productvariant'),
        ),
    ]
