# Generated by Django 5.0.7 on 2024-08-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coupon_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
