# Generated by Django 5.0.7 on 2026-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_order_payment_expires_at_order_stock_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reject_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
